### ISSUE TITLE
How about implementing a search box?

### ISSUE THREAD

**Issue by ghoshriju33** [sumitkolhe/TheIndex#1]
Would love to see a search box using which we can search for the resource using fuzzy search logic.

**Comment by sumitkolhe** [comment]
Seems like a good idea. Will try to implement it.

**Comment by ghoshriju33** [comment]
Thanks. Looking forward to it 👍

**Comment by sumitkolhe** [comment]
I've made a rudimentary search mechanism for the next update. Though, since the resources are already arranged category / keyword wise, doing a search still yeilds more or less the same results you'd find in the category sections.

**Comment by ghoshriju33** [comment]
Search would come in handy if if remember a part of the description. Suppose I need some resources only for wireframes. The defined category is UI graphics. There is one entry called Sketch App Sources. Its description is: 
> Sketch UIs, wireframes, icons and much more...
Then if I search for wireframe, the result will immediately pop out.

**Comment by sumitkolhe** [comment]
Yup. Basic implementation is done. Not fuzzy as of now, maybe will improve it later on.. But it works fine as of now

**Comment by ghoshriju33** [comment]
Sure. Waiting for the next update to be live.
And I don't know about others but this will definitely benefit me a lot.

**Comment by sumitkolhe** [comment]
Sure. You are welcome to PR any new features you want in this project as well.

**Comment by sumitkolhe** [comment]
@ghoshriju33  Search function implemented.

**Comment by ghoshriju33** [comment]
I saw it. The function is really helpful. Trust me. And if possible you can add enter key support too.

**Comment by sumitkolhe** [comment]
enter key support is added but fpr some reason it is not working. i'll try to fix it
